name: leaderboard-backend
version: '3.8'
services:
  server:
    ports:
      - 8001:8000
      - 5679:5678
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    networks:
      - leaderboard-network
      - shared-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python worker.py
    env_file:
      - .env
    networks:
      - leaderboard-network
      - shared-network

networks:
  shared-network:
    external: true
  leaderboard-network:
    external: false
